using System;

namespace DotNext.Net.Cluster.Consensus.Raft.Http
{
    using IClientMetricsCollector = Metrics.IClientMetricsCollector;

    /// <summary>
    /// Contains a set of callbacks that can be used to report
    /// runtime metrics generated by HTTP-specific implementation of Raft cluster node.
    /// </summary>
    /// <remarks>
    /// You need to register singleton service of type <see cref="MetricsCollector"/>
    /// to collect metrics produced by Raft node.
    /// </remarks>
    public class HttpMetricsCollector : MetricsCollector, IClientMetricsCollector
    {
        /// <summary>
        /// Reports about HTTP response time.
        /// </summary>
        /// <param name="value">The response time.</param>
        public virtual void ReportResponseTime(TimeSpan value)
        {
        }
    }
}