variables:
  Solution: src/DotNext.slnx
  TestFolder: src/DotNext.Tests
  TestProject: $(TestFolder)/DotNext.Tests.csproj
  AotTestFolder: src/DotNext.Aot.Tests
  AotTestProject: $(AotTestFolder)/DotNext.Aot.Tests.csproj
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: false
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
trigger:
  - master
  - develop
stages:
  - stage: Tests
    jobs:
      - job: Windows
        pool:
          vmImage: windows-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Packages
            inputs:
              command: restore
              projects: '$(Solution)'
              feedsToUse: 'config'
              nugetConfigPath: 'NuGet.config'
          - task: DotNetCoreCLI@2
            displayName: Test Debug
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(TestProject)
              arguments: --configuration Debug --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on Windows'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact'
            artifact: coverage-windows
          - task: DotNetCoreCLI@2
            displayName: Test Debug AOT Emul
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(AotTestProject)
              arguments: --configuration Debug --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on Windows (NoDynamicCode)'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact (NoDynamicCode)'
            artifact: coverage-windows-aot
      - job: Linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Packages
            inputs:
              command: restore
              projects: '$(Solution)'
              feedsToUse: 'config'
              nugetConfigPath: 'NuGet.config'
              arguments: --configuration Debug
          - task: DotNetCoreCLI@2
            displayName: Publish AOT Tests
            inputs:
              command: publish
              publishWebProjects: false
              zipAfterPublish: false
              projects: $(AotTestProject)
              arguments: --configuration Release --output $(AotTestFolder)/bin/aot -p:PublishAot=true
          - task: CmdLine@2
            displayName: Run AOT Tests
            inputs:
              workingDirectory: $(AotTestFolder)/bin/aot/DotNext.Aot.Tests
              script: ./DotNext.Aot.Tests --report-trx --report-trx-filename aot-tests.trx --results-directory $(Agent.TempDirectory)/AotTestResults
          - task: PublishTestResults@2
            displayName: 'Publish AOT Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: VSTest
              testResultsFiles: '$(Agent.TempDirectory)/AotTestResults/*.trx'
              testRunTitle: 'Debug on Linux (AOT)'
          - task: DotNetCoreCLI@2
            displayName: Test Debug
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(TestProject)
              arguments: --configuration Debug --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on Linux'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact'
            artifact: coverage-linux
          - task: DotNetCoreCLI@2
            displayName: Test Debug AOT Emul
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(AotTestProject)
              arguments: --configuration Debug --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on Linux (NoDynamicCode)'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact (NoDynamicCode)'
            artifact: coverage-linux-aot
      - job: MacOS
        pool:
          vmImage: macOS-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore Packages
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 3
            inputs:
              command: restore
              projects: '$(Solution)'
              feedsToUse: 'config'
              nugetConfigPath: 'NuGet.config'
              arguments: --configuration Debug
          - task: DotNetCoreCLI@2
            displayName: Test Debug
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(TestProject)
              arguments: --configuration Debug --output Detailed --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on MacOS'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact'
            artifact: coverage-macos
          - task: DotNetCoreCLI@2
            displayName: Test Debug AOT Emul
            timeoutInMinutes: 10
            retryCountOnTaskFailure: 2
            inputs:
              command: test
              projects: $(AotTestProject)
              arguments: --configuration Debug --output Detailed --coverage --coverage-output-format cobertura --coverage-output $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
              nobuild: false
              testRunTitle: 'Debug on MacOS (NoDynamicCode)'
              publishTestResults: true
          - publish: $(Agent.TempDirectory)/CoverageResults/coverage.cobertura.xml
            displayName: 'Publish coverage artifact (NoDynamicCode)'
            artifact: coverage-macos-aot
      - job: MergeCoverage
        dependsOn:
          - Windows
          - Linux
          - MacOS
        condition: succeededOrFailed()
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            displayName: Download Windows coverage
            artifact: coverage-windows
          - download: current
            displayName: Download Linux coverage
            artifact: coverage-linux
          - download: current
            displayName: Download MacOS coverage
            artifact: coverage-macos
          - download: current
            displayName: Download Windows coverage (NoDynamicCode)
            artifact: coverage-windows-aot
          - download: current
            displayName: Download Linux coverage (NoDynamicCode)
            artifact: coverage-linux-aot
          - download: current
            displayName: Download MacOS coverage (NoDynamicCode)
            artifact: coverage-macos-aot
          - task: PublishCodeCoverageResults@2
            displayName: 'Publish merged code coverage'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(Pipeline.Workspace)/coverage-*/coverage.cobertura.xml
  - stage: BuildPackages
    condition: and(succeeded('Tests'), eq(variables.isMain, true))
    jobs:
      - job: PackAndPublish
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            displayName: Pack
            inputs:
              command: pack
              nobuild: false
              configuration: Release
              packDirectory: $(Build.ArtifactStagingDirectory)/packages
              verbosityPack: Minimal
              packagesToPack: src/DotNext/DotNext.csproj;src/DotNext.IO/DotNext.IO.csproj;src/DotNext.Metaprogramming/DotNext.Metaprogramming.csproj;src/DotNext.Reflection/DotNext.Reflection.csproj;src/DotNext.Threading/DotNext.Threading.csproj;src/DotNext.Unsafe/DotNext.Unsafe.csproj;src/DotNext.MaintenanceServices/DotNext.MaintenanceServices.csproj;src/cluster/DotNext.Net.Cluster/DotNext.Net.Cluster.csproj;src/cluster/DotNext.AspNetCore.Cluster/DotNext.AspNetCore.Cluster.csproj
          - publish: config
            displayName: Publish signing config
            artifact: config
          - publish: $(Build.ArtifactStagingDirectory)/packages
            displayName: Publish artifacts
            artifact: packages
  - stage: SignPackages
    condition: succeeded('BuildPackages')
    jobs:
      - job: CodeSign
        pool:
          vmImage: windows-latest
        variables:
          - group: Sign Client Credentials
        steps:
          - task: DotNetCoreCLI@2
            displayName: Install SignTool tool
            inputs:
              command: custom
              custom: tool
              arguments: install --tool-path . sign --prerelease
          - download: current
            displayName: Download packages
            artifact: packages
          - download: current
            displayName: Download signing file list
            artifact: config
          - pwsh: |
              .\sign code azure-key-vault `
              "**/*.nupkg" `
              --base-directory "$(Pipeline.Workspace)\packages" `
              --file-list "$(Pipeline.Workspace)\config\filelist.txt" `
              --publisher-name ".NEXT Contributors" `
              --description ".NEXT Family of Libraries" `
              --description-url "https://github.com/dotnet/dotNext" `
              --azure-key-vault-tenant-id "$(SignTenantId)" `
              --azure-key-vault-client-id "$(SignClientId)" `
              --azure-key-vault-client-secret '$(SignClientSecret)' `
              --azure-key-vault-certificate "$(SignKeyVaultCertificate)" `
              --azure-key-vault-url "$(SignKeyVaultUrl)"
            displayName: Sign packages
          - publish: $(Pipeline.Workspace)/packages
            displayName: Publish Signed Packages
            artifact: SignedPackages