#!/usr/bin/env python3
"""Generates llms.txt (https://llmstxt.org) from docfx toc.yml files.

Articles are linked by their raw Markdown sources, which GitHub Pages serves from the docs/ folder.
API reference is linked by namespace pages; run 'docfx metadata' first to get api/toc.yml.
Usage: python3 llms.py [--base-url URL] [--output FILE]
"""

import argparse
import json
import posixpath
import re
from pathlib import Path

import yaml

DOCS_DIR = Path(__file__).resolve().parent
DEFAULT_BASE_URL = 'https://dotnet.github.io/dotNext/'


class Generator:
    def __init__(self, base_url):
        self.base_url = base_url.rstrip('/') + '/'
        self.sections = []  # list of (title, [lines])
        self.resources = []

    def article_url(self, path):
        # Raw Markdown is served from the 'docs/' folder of the gh-pages branch
        return f'{self.base_url}docs/{path}'

    def page_url(self, path):
        return self.base_url + path

    @staticmethod
    def load_toc(path):
        with open(DOCS_DIR / path, encoding='utf-8') as f:
            toc = yaml.safe_load(f) or []
        # TOC is either a list of entries or an object with 'items' property
        return toc.get('items', []) if isinstance(toc, dict) else toc

    def link(self, name, folder, href):
        if re.match(r'^[a-z]+://', href):
            return f'- [{name}]({href})'
        path = posixpath.normpath(posixpath.join(folder, href))
        if path.endswith('.md'):
            return f'- [{name}]({self.article_url(path)})'
        return f'- [{name}]({self.page_url(path)})'

    def items(self, entries, folder, depth=0):
        lines = []
        for entry in entries:
            name, href = entry['name'], entry.get('href')
            if href:
                lines.append('  ' * depth + self.link(name, folder, href))
            elif entry.get('items'):
                lines.append('  ' * depth + f'- {name}')
            lines.extend(self.items(entry.get('items', []), folder, depth + 1))
        return lines

    def folder(self, name, folder):
        toc = folder + '/toc.yml'
        if not (DOCS_DIR / toc).exists():
            print(f'warning: {toc} not found, section "{name}" is skipped')
            return

        entries = self.load_toc(toc)
        if all('uid' in entry for entry in entries):
            # TOC generated by 'docfx metadata', top-level entries are namespaces
            self.sections.append((name, [f'- [{e["name"]}]({self.page_url(f"{folder}/{e["uid"]}.html")})' for e in entries]))
            return

        # Each top-level group of the nested TOC becomes a separate section
        for entry in entries:
            lines = []
            if 'href' in entry:
                lines.append(self.link('Overview', folder, entry['href']))
            lines.extend(self.items(entry.get('items', []), folder))
            self.sections.append((entry['name'], lines))

    def run(self):
        for entry in self.load_toc('toc.yml'):
            name, href = entry['name'], entry.get('href')
            if href and href.endswith('/') and not re.match(r'^[a-z]+://', href):
                self.folder(name, href.rstrip('/'))
            elif href:
                self.resources.append(self.link(name, '', href))
            else:
                self.sections.append((name, self.items(entry.get('items', []), '')))

    def render(self):
        with open(DOCS_DIR / 'docfx.json', encoding='utf-8') as f:
            title = json.load(f)['build']['globalMetadata']['_appTitle']

        out = [f'# {title}', '', f'> {intro()}', '', f'- [Overview]({self.article_url("index.md")})', '']
        for name, lines in self.sections + [('Resources', self.resources)]:
            if lines:
                out += [f'## {name}', '', *lines, '']
        return '\n'.join(out)


def intro():
    """First paragraph of index.md that follows the title."""
    text = (DOCS_DIR / 'index.md').read_text(encoding='utf-8')
    paragraphs = [p.strip() for p in re.split(r'\n\s*\n', text)]
    return next(p for p in paragraphs[1:] if p and not p.startswith(('#', '<', '!', '*')))


def main():
    parser = argparse.ArgumentParser(description='Generates llms.txt from docfx TOC files')
    parser.add_argument('--base-url', default=DEFAULT_BASE_URL)
    parser.add_argument('--output', default=str(DOCS_DIR / 'llms.txt'))
    args = parser.parse_args()

    generator = Generator(args.base_url)
    generator.run()
    Path(args.output).write_text(generator.render(), encoding='utf-8')
    print(f'{args.output} is generated')


if __name__ == '__main__':
    main()
